[providers]
python = "3.11"

[phases.setup]
aptPkgs = [
  "...",
  "poppler-utils",
  "tesseract-ocr",
  "ghostscript",
  "fontconfig",
  "fonts-dejavu-core",
  "fonts-liberation"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
